---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
spec:
  releaseName: jaeger
  interval: 1m
  chart:
    spec:
      chart: jaeger
      version: "0.57.1"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: observability-system
  values:

    provisionDataStore:
      cassandra: false
    allInOne:
      enabled: true
    storage:
      type: none
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false